[pytest]
addopts = --junitxml=report.xml
testpaths =
    tests

python_files =
    test_*.py

[pytest-alembic]
script_location = alembic/versions
target_metadata = app.database.Base.metadata
start_revision = base
sqlalchemy.url = sqlite:///alembic/alembic.db

# Add a custom initialization hook to include the project root in the Python path
init_args = -c "import sys; import os; sys.path.insert(0, os.getcwd())"